wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1653290517
    t:
      1:
      - 2
      - 3
      - 5
      - 6
      - 53
      - 55
      3:
      - 13
      - 16
      4: 3.8.13
      5: 0.12.15
      8:
      - 1
      - 5
activation:
  desc: null
  value: swish
activation_type:
  desc: null
  value: swish
batch_size:
  desc: null
  value: 1024
dropout:
  desc: null
  value: 0.8
epochs:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.003
nn_nodes:
  desc: null
  value:
  - 256
  - 128
  - 64
optimizer:
  desc: null
  value: adam
seed:
  desc: null
  value: 42
