name: tensorflow_env
channels:
  - apple
  - plotly
  - conda-forge
dependencies:
  - alembic=1.7.7=pyhd8ed1ab_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py38h33210d7_2
  - atk-1.0=2.36.0=heb41896_4
  - attrs=21.4.0=pyhd8ed1ab_0
  - autopage=0.5.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bleach=5.0.0=pyhd8ed1ab_0
  - brotli=1.0.9=h1c322ee_7
  - brotli-bin=1.0.9=h1c322ee_7
  - bzip2=1.0.8=h3422bc3_4
  - c-ares=1.18.1=h3422bc3_0
  - ca-certificates=2021.10.8=h4653dfc_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=h3e596be_1011
  - cffi=1.15.0=py38hc67bbb8_0
  - cliff=3.10.1=pyhd8ed1ab_0
  - cloudpickle=2.0.0=pyhd8ed1ab_0
  - cmaes=0.8.2=pyh44b312d_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.6.0=py38hea55cf5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - expat=2.4.8=h6b3803e_0
  - flit-core=3.7.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=hfb34624_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.33.3=py38he5c2ac2_0
  - freetype=2.10.4=h17b34a0_1
  - fribidi=1.0.10=h27ca646_0
  - gdk-pixbuf=2.42.8=hdded42e_0
  - gettext=0.19.8.1=h049c9fb_1008
  - giflib=5.2.1=h27ca646_2
  - graphite2=1.3.13=h9f76cd9_1001
  - graphviz=3.0.0=hd4d4665_1
  - greenlet=1.1.2=py38hea55cf5_2
  - grpcio=1.45.0=py38hdbc235a_0
  - gtk2=2.24.33=h57013de_2
  - gts=0.7.6=h4b6d4d6_2
  - h5py=3.6.0=nompi_py38hacf61ce_100
  - harfbuzz=4.2.1=hd36a07e_0
  - hdf5=1.12.1=nompi_hd9dbc9e_104
  - icu=70.1=h6b3803e_0
  - importlib-metadata=4.11.3=py38h10201cd_1
  - importlib_resources=5.7.1=pyhd8ed1ab_0
  - ipykernel=6.13.0=py38h2cb4d76_0
  - ipython=7.33.0=py38h10201cd_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.7.0=pyhd8ed1ab_0
  - jbig=2.1=h3422bc3_2003
  - jedi=0.18.1=py38h10201cd_1
  - jinja2=3.1.2=pyhd8ed1ab_0
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h1c322ee_1
  - jsonschema=4.5.1=pyhd8ed1ab_0
  - jupyter=1.0.0=py38h10201cd_7
  - jupyter_client=7.3.0=pyhd8ed1ab_0
  - jupyter_console=6.4.3=pyhd8ed1ab_0
  - jupyter_core=4.9.2=py38h10201cd_0
  - jupyterlab_widgets=1.1.0=pyhd8ed1ab_0
  - kiwisolver=1.4.2=py38h0f71543_1
  - krb5=1.19.3=he492e65_0
  - lcms2=2.12=had6a04f_0
  - lerc=3.0=hbdafb3b_0
  - libblas=3.9.0=14_osxarm64_openblas
  - libbrotlicommon=1.0.9=h1c322ee_7
  - libbrotlidec=1.0.9=h1c322ee_7
  - libbrotlienc=1.0.9=h1c322ee_7
  - libcblas=3.9.0=14_osxarm64_openblas
  - libcurl=7.83.0=h7965298_0
  - libcxx=14.0.3=h6a5c8ee_0
  - libdeflate=1.10=h3422bc3_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h642e427_1
  - libffi=3.4.2=h3422bc3_5
  - libgd=2.3.3=hede1055_3
  - libgfortran=5.0.0.dev0=11_0_1_hf114ba7_23
  - libgfortran5=11.0.1.dev0=hf114ba7_23
  - libglib=2.70.2=h67e64d8_4
  - libiconv=1.16=h642e427_0
  - liblapack=3.9.0=14_osxarm64_openblas
  - libnghttp2=1.47.0=hf30690b_0
  - libopenblas=0.3.20=openmp_h2209c59_0
  - libpng=1.6.37=hf7e6567_2
  - librsvg=2.54.1=ha2634a2_0
  - libsodium=1.0.18=h27ca646_1
  - libssh2=1.10.0=h7a5bd25_2
  - libtiff=4.3.0=h77dc3b6_3
  - libtool=2.4.6=hbdafb3b_1008
  - libwebp=1.2.2=h0d20362_0
  - libwebp-base=1.2.2=h3422bc3_1
  - libxcb=1.13=h9b22ae9_1004
  - libxml2=2.9.14=h035c1df_0
  - libzlib=1.2.11=h90dfc92_1014
  - lightgbm=3.3.2=py38hb2dfaa5_0
  - llvm-openmp=14.0.3=hd125106_0
  - lz4-c=1.9.3=hbdafb3b_1
  - mako=1.2.0=pyhd8ed1ab_1
  - markupsafe=2.1.1=py38h33210d7_1
  - matplotlib=3.5.1=py38h150bfb4_0
  - matplotlib-base=3.5.1=py38hb140015_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mistune=0.8.4=py38hea4295b_1005
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbconvert=5.6.1=pyhd8ed1ab_2
  - nbformat=5.4.0=pyhd8ed1ab_0
  - ncurses=6.3=h07bb92c_1
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - notebook=6.4.11=pyha770c72_0
  - numpy=1.21.5=py38hb29071a_0
  - openjpeg=2.4.0=h062765e_1
  - openssl=3.0.3=ha287fd2_0
  - optuna=2.10.0=pyhd8ed1ab_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.2=py38h55de146_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.50.7=h9fd36ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - patsy=0.5.2=pyhd8ed1ab_0
  - pbr=5.9.0=pyhd8ed1ab_0
  - pcre=8.45=hbdafb3b_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.1.0=py38h7ff1586_2
  - pip=22.0.4=pyhd8ed1ab_0
  - pixman=0.40.0=h27ca646_0
  - plotly=5.7.0=py_0
  - prettytable=3.3.0=pyhd8ed1ab_0
  - prometheus_client=0.14.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.29=pyha770c72_0
  - prompt_toolkit=3.0.29=hd8ed1ab_0
  - psutil=5.9.0=py38h33210d7_1
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydot=1.4.2=py38h10201cd_1
  - pygments=2.12.0=pyhd8ed1ab_0
  - pyparsing=3.0.8=pyhd8ed1ab_0
  - pyperclip=1.8.2=pyhd8ed1ab_2
  - pyrsistent=0.18.1=py38h33210d7_1
  - python=3.8.13=hd3575e6_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.15.3=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytz=2022.1=pyhd8ed1ab_0
  - pyyaml=6.0=py38h33210d7_4
  - pyzmq=22.3.0=py38h5f86631_2
  - readline=8.1=hedafd6a_0
  - scikit-learn=1.0.2=py38h2cd4032_0
  - scipy=1.8.0=py38hd0c9ec0_1
  - seaborn=0.11.2=hd8ed1ab_0
  - seaborn-base=0.11.2=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=62.1.0=py38h10201cd_0
  - spyder-kernels=2.3.0=py38h10201cd_0
  - sqlalchemy=1.4.36=py38he5c2ac2_0
  - sqlite=3.38.5=h40dfcc0_0
  - statsmodels=0.13.2=py38h691f20f_0
  - stevedore=3.5.0=py38h10201cd_3
  - tenacity=8.0.1=pyhd8ed1ab_0
  - tensorflow-deps=2.8.0=0
  - terminado=0.13.3=py38h10201cd_1
  - testpath=0.6.0=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.12=he1e0b03_0
  - tornado=6.1=py38h33210d7_3
  - tqdm=4.64.0=pyhd8ed1ab_0
  - traitlets=5.1.1=pyhd8ed1ab_0
  - tscv=0.1.2=pyhd8ed1ab_0
  - unicodedata2=14.0.0=py38h33210d7_1
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=3.6.0=py38h10201cd_0
  - wurlitzer=3.0.2=pyhd8ed1ab_2
  - xorg-libxau=1.0.9=h27ca646_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xz=5.2.5=h642e427_1
  - yaml=0.2.5=h3422bc3_2
  - zeromq=4.3.4=hbdafb3b_1
  - zipp=3.8.0=pyhd8ed1ab_0
  - zlib=1.2.11=h90dfc92_1014
  - zstd=1.5.2=h861e0a7_0
  - pip:
    - absl-py==1.0.0
    - astunparse==1.6.3
    - autots==0.4.0
    - cachetools==5.0.0
    - certifi==2021.10.8
    - charset-normalizer==2.0.12
    - click==8.1.2
    - cmd2==2.4.1
    - cmdstanpy==0.9.68
    - colorlog==6.6.0
    - convertdate==2.4.0
    - cython==0.29.28
    - docker-pycreds==0.4.0
    - ephem==4.1.3
    - flatbuffers==2.0
    - gast==0.5.3
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.6.3
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - hijri-converter==2.2.3
    - holidays==0.13
    - idna==3.3
    - keras==2.8.0
    - keras-preprocessing==1.1.2
    - korean-lunar-calendar==0.2.1
    - libclang==13.0.0
    - lunarcalendar==0.0.9
    - markdown==3.3.6
    - oauthlib==3.2.0
    - opt-einsum==3.3.0
    - pathtools==0.1.2
    - promise==2.3
    - prophet==1.0.1
    - protobuf==3.20.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pymeeus==0.5.11
    - pystan==2.19.1.1
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - sentry-sdk==1.5.9
    - setproctitle==1.2.2
    - setuptools-git==1.2
    - shortuuid==1.0.8
    - six==1.15.0
    - smmap==5.0.0
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow-macos==2.8.0
    - tensorflow-metal==0.4.0
    - termcolor==1.1.0
    - tf-estimator-nightly==2.8.0.dev2021122109
    - typing-extensions==4.1.1
    - ujson==5.2.0
    - urllib3==1.26.9
    - wandb==0.12.15
    - werkzeug==2.1.1
    - wrapt==1.14.0
    - xgboost==1.5.2
prefix: /Users/dylan/miniforge3/envs/tensorflow_env
