wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1652159087
    t:
      1:
      - 2
      - 3
      - 5
      - 6
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 3
      - 8
      - 13
      - 16
      4: 3.8.13
      5: 0.12.15
      8:
      - 1
      - 4
      - 5
activation_type:
  desc: null
  value: swish
batch_size:
  desc: null
  value: 32
dropout:
  desc: null
  value: 0.5
epochs:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.001
nn_nodes:
  desc: null
  value:
  - 32
  - 32
  - 32
optimizer:
  desc: null
  value: adam
seed:
  desc: null
  value: 42
