wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1652157801
    t:
      1:
      - 2
      - 3
      - 5
      - 6
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 13
      - 32
      4: 3.8.13
      5: 0.12.15
      8:
      - 1
      - 4
      - 5
